280 | Adding notification image loading handler
mindbox-moscow/android-sdk pull request #238
Opened 2022-07-15 12:47 UTC by umbrellait-oleg-korelin

https://trello.com/c/9OpkiKCU

https://github.com/mindbox-moscow/issues-mobile-sdk/issues/269

2022-07-15 18:43 UTC, umbrellait-artem-petrov requested changes

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
>  import cloud.mindbox.mobile_sdk.pushes.PushNotificationManager
Если со * импорт, то можно и этот убрать

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +         * Optional image to replace the desired one
Через `@param placeholder - Optional image to replace the desired one`. + Что значит desired one?
+ Стоит дать клиентам возможность передавать картинку не как Bitmap, а как drawable или `@DrawableRes`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +         * Delay before retry in milliseconds
Аналогично через `@params`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +         * Delay before retry in milliseconds
Аналогично в через `@params`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +         * Optional image to replace the desired one
Аналогично в через `@params`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val placeholder: Bitmap? = null
Передавать как Drawable или `@DrawableRes`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +     * @param message Notification message
Добавь параметр `context - android context` для полноты картины

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +        companion object {
В начало класса, пустые строки перед и после константы

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +
Лишняя пустая строка

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +            val url = message.imageUrl ?: return null
Лучше без early return. Я б переписал на
```
override fun onLoadImage(
    context: Context,
    message: RemoteMessage,
    state: MessageHandlingState
): Bitmap?  = message.imageUrl?.let { url ->
    val connection = URL(url).openConnection().apply {
        readTimeout = IMAGE_CONNECTION_TIMEOUT
        connectTimeout = IMAGE_CONNECTION_TIMEOUT
    }
    BitmapFactory.decodeStream(connection.getInputStream())
}
```

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingState.kt
> +)
Комменты к пропертям конструктора лучше вынести в комментарий над всем классом через `@param`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            kotlin.runCatching {
Через LoggingExceptionHandler.runCatching

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    state = state
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        state: MessageHandlingState
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            message = "Notify message ${remoteMessage.uniqueKey} started with state $state"
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        defaultActivity: Class<out Activity>
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        notificationId: Int
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingState.kt
> +    val isNotificationWasShown: Boolean
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +            error: Throwable
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +            state: MessageHandlingState
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +        error: Throwable
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val placeholder: Bitmap? = null
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val placeholder: Bitmap? = null
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val image: Result<Bitmap?> = withContext(Dispatchers.IO) {
Нужно явное указание типа?

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val fallback: ImageFallback? = image.exceptionOrNull()?.let { error ->
Нужно явное указание типа?

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                exception = error
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                error = error
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                            "image loading - $it"
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    state = state
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    defaultActivity = defaultActivity
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    state = state.copy(isNotificationWasShown = true)
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    defaultActivity = defaultActivity
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                }
можно
```
image?.let {
    setImage(image, title, text)
} 
    ?: setText(text)
```

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
>      private const val INITIAL_DELAY = 120L
Пустая строка

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +    private const val NOTIFICATION_WORKER_TAG = "NotificationWorker"
Лучше `MindboxNotificationWorkManager${MindboxPreferences.hostAppName}"`

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +        state: MessageHandlingState
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        text: String?
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        defaultActivity: Class<out Activity>
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    message = "Notify message ${remoteMessage.uniqueKey}: successfully notified"
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                    defaultActivity = defaultActivity
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +            state = state
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +    workerParams: WorkerParameters
запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        val data = inputData
Зачем лишняя переменная?

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        val notificationId: Int = data.getInt(KEY_NOTIFICATION_ID, EMPTY_INT)
Зачем явный тип

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        defaultValue = Result.failure()
Запятая

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        val notificationId: Int = data.getInt(KEY_NOTIFICATION_ID, EMPTY_INT)
И нижп тоже. Лучше через дженерики, где необходимо

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            ?.mapNotNull {  (key, value) ->
лишний пробел

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +                    @Suppress("unchecked_cast")
Убери, пусть так будет)

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            }
Отступ на 1 меньше

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +                    @Suppress("unchecked_cast")
Убери)

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            return LoggingExceptionHandler.runCatching(defaultValue = null) {
Через =

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        private fun <T : Any> T.serialize(): String? {
gson плохо обращается с числами, у него привычка int сохранять как double. Проверь этот момент наверняка. Лучше всего передавать число строкой

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            return LoggingExceptionHandler.runCatching(defaultValue = null) {
через =

2022-07-15 18:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            state: MessageHandlingState
запятая

2022-07-15 18:48 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            notificationId = Random.nextInt(),
Нужна проверка на то, что notification с таким id не отображается сейчас. Если отображается - перегенерить id, пока мы не добудем уникальный

2022-07-15 18:48 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                isNotificationWasShown = false
запятая

2022-07-15 18:48 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            )
запятая

2022-07-15 18:51 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +    }
```
= notificationManager.activeNotifications
   .find { it.id == notificationId } != null
```

2022-07-15 18:59 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +    internal var remoteMessageHandling: MessageHandlingCallback = MessageHandlingCallback.Default()
Как насчёт передавать это необязательным параметром (по дефолту = Default()) в методе handleRemoteMessage? Тогда надо вручную оставить перегрузку со старой сигнатурой, чтобы не поломался java-код

2022-07-15 19:07 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            is ImageFallback.Retry -> {
Давай каждую ветку в отдельный метод

2022-07-15 19:11 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L,
Эта задержка юзается в воркменеджере. Стоит добавить в коммент, что если delay < 10_000, то он будет 10_000

2022-07-15 19:11 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L
Эта задержка юзается в воркменеджере. Стоит добавить в коммент, что если delay < 10_000, то он будет 10_000

2022-07-15 19:12 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L
Эта задержка юзается в воркменеджере. Стоит добавить в коммент, что если delay < 10_000, то он будет 10_000

2022-07-15 19:15 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            val activitiesString: String? = activities?.mapValues { it.value.name }?.serialize()
it.value.canonicalName

2022-07-15 19:15 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            val defaultActivityString: String? = defaultActivity.name
defaultActivity.canonicalName

2022-07-15 20:39 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +                }
Вкусовщина, можно оставить

2022-07-18 07:54 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val image: Result<Bitmap?> = withContext(Dispatchers.IO) {
Так читабельнее

2022-07-18 07:55 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val fallback: ImageFallback? = image.exceptionOrNull()?.let { error ->
Так читабельнее

2022-07-18 08:07 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +    private const val NOTIFICATION_WORKER_TAG = "NotificationWorker"
Fixed

2022-07-18 08:13 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        val data = inputData
Fixed

2022-07-18 08:19 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        val notificationId: Int = data.getInt(KEY_NOTIFICATION_ID, EMPTY_INT)
Fixed

2022-07-18 08:22 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +                    @Suppress("unchecked_cast")
Тогда больно глазам

2022-07-18 09:02 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            notificationId = Random.nextInt(),
Добавил доп класс для генерации

2022-07-18 09:10 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +    internal var remoteMessageHandling: MessageHandlingCallback = MessageHandlingCallback.Default()
Этот метод вызывается один раз при прилете пуша. В случае ошибки загрузки картинки мы не можем передать этот калбэк в воркер для перезапуска.

2022-07-18 10:03 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L,
Вроде бы это так работает только при retry в воркменеджере. В initialDelay можно и 0 передать

2022-07-18 10:03 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L
Вроде бы это так работает только при retry в воркменеджере. В initialDelay можно и 0 передать

2022-07-18 10:17 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +         * Optional image to replace the desired one
"Опциональная картинка которая земенит ожидаемую"
На сколько я помню решили что останется Bitmap

2022-07-18 10:46 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            is ImageFallback.Retry -> {
Fixed

2022-07-18 11:57 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +         * Optional image to replace the desired one
Давай добавим "... if downloading failed"

2022-07-18 12:00 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/ImageFallback.kt
> +        val delay: Long = 0L,
Согласен, ты прав

2022-07-18 12:03 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val image: Result<Bitmap?> = withContext(Dispatchers.IO) {
В Ide есть подсветка синтаксиса. Лучше опускать явные типы, если они не нужны для компиляции

2022-07-18 12:04 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val fallback: ImageFallback? = image.exceptionOrNull()?.let { error ->
В Ide есть подсветка синтаксиса. Лучше опускать явные типы, если они не нужны для компиляции

2022-07-18 12:34 UTC, umbrellait-artem-petrov requested changes

2022-07-18 12:34 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +     * Set callback to handle some events in [handleRemoteMessage]
Добавь описание, где и как нужно использовать

2022-07-18 12:34 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingCallback.kt
> +    ): ImageRetryStrategy
Добавить пустую строку

2022-07-18 12:38 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +    private const val NOTIFICATION_WORKER_TAG = "NotificationWorker"
Открыл другой тред

2022-07-18 14:29 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Generator.kt
> +        return System.currentTimeMillis().toInt() + atomicInteger.incrementAndGet()
Снимается, коллизий быть не будет

2022-07-18 15:36 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        val fallback: ImageFallback? = image.exceptionOrNull()?.let { error ->
Fixed

2022-07-18 15:38 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MessageHandlingDefault.kt
> +        return message.imageUrl?.let { url ->
Fixed

2022-07-18 15:44 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        return Generator.generateInt()
Fixed

2022-07-19 06:08 UTC, umbrellait-oleg-korelin commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +            is ImageRetryStrategy.Retry -> {
У всех функций приличное кол-во параметров и это точно лучше выглядит внутри скобок

2022-07-19 07:35 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +        imageFailureHandler: MindboxImageFailureHandler = PushNotificationManager.messageHandler.imageFailureHandler,
Давай параметры местами поменяем. imageFailureHandler будет чаще использоваться, чем imageLoader. Вызывать метод можно будет тогда не только через `setMessageHandling(imageFailureHandler = someHandler)`, но и просто `imageFailureHandler(someHandler)`

2022-07-19 07:39 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MindboxImageFailureHandlerDefaults.kt
> +    return ApplyDefaultStrategyImpl(defaultImage = defaultImage)
По всему файлу - равно

2022-07-19 07:40 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/MindboxImageLoaderDefault.kt
> +val MindboxImageLoader.Companion.Default: MindboxImageLoader
Давай тоже в MindboxImageLoader перенесем

2022-07-19 07:43 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Generator.kt
> +        return System.currentTimeMillis().toInt() + atomicInteger.incrementAndGet()
Через =

2022-07-19 16:49 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +        return "$NOTIFICATION_WORKER_TAG-$notificationId"
🌚

2022-07-19 16:50 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +            LoggingExceptionHandler.runCatching(defaultValue = null) {
1. Нужно ли Any?
2. В одну строку или 
```
private fun <T : Any> T.serialize(): String? = LoggingExceptionHandler.runCatching(
    defaultValue = null,
) {
    gson.toJson(this)
}
```

2022-07-19 16:50 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +        private inline fun <reified T : Any> String.deserialize(): T? =
Аналогично

2022-07-19 16:51 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/utils/Generator.kt
> +        System.currentTimeMillis().toInt() + atomicInteger.incrementAndGet()
fun generateUniqueInt() = System.currentTimeMillis().toInt() + 
atomicInteger.incrementAndGet()

2022-07-19 19:11 UTC, umbrellait-artem-petrov approved these changes

2022-07-28 09:51 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/pushes/PushNotificationManager.kt
> +        return "Notify message ${message.uniqueKey}: $log"
=

2022-07-28 09:59 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxBackgroundWorkManager.kt
> +                TimeUnit.MILLISECONDS
,

2022-07-28 10:00 UTC, umbrellait-artem-petrov commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxNotificationWorker.kt
> +                    exception = e
,

2022-07-28 13:39 UTC, merged