Release 1.0.0
mindbox-moscow/android-sdk pull request #78
Opened 2021-03-10 12:15 UTC by umbrella-roman-parfinenko

2021-03-10 12:25 UTC, provan requested changes

2021-03-10 12:25 UTC, provan commented on app/src/main/java/com/mindbox/androidsdk/PushokMessagingService.kt
> +class PushokMessagingService : FirebaseMessagingService() {
@umbrellait-alexandra-batanova что у нас в сдк делает пушок?

2021-03-17 09:11 UTC, peter-nikitin commented on app/src/main/java/com/mindbox/androidsdk/PushokMessagingService.kt
> +class PushokMessagingService : FirebaseMessagingService() {
Ожидаем исправление 17.03

2021-03-17 20:55 UTC, umbrellait-alexandra-batanova commented on app/src/main/java/com/mindbox/androidsdk/PushokMessagingService.kt
> +class PushokMessagingService : FirebaseMessagingService() {
убран модуль приложения из проекта и добавлен в .gitignore

2021-03-22 10:30 UTC, peter-nikitin commented on app/src/main/java/com/mindbox/androidsdk/PushokMessagingService.kt
> +class PushokMessagingService : FirebaseMessagingService() {
@provan подскажи, когда сможем закрыть комменты и смержить?

2021-03-24 23:22 UTC, provan requested changes

2021-03-24 23:22 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            if ((isTokenAvailable && firebaseToken != MindboxPreferences.firebaseToken) || isNotificationEnabled != MindboxPreferences.isNotificationEnabled) {
если передали в токен пустую строку и изменился статус разрешения, то отправим пустой токен и перетрем у себя

2021-03-24 23:22 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            MindboxEventManager.sendEventsIfExist(context)
мы же запускаем здесь отправку, хотя первичная инициализация могла еще не завершиться.
вижу здесь гонку

2021-03-24 23:22 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            DbManager.saveConfigurations(configuration)
давай еще раз, зачем нам нужно сохранять конфигурацию двумя разными способами?
это багоемко, вижу тут риски.
можем оставить только одну?

2021-03-24 23:22 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
> +    private fun generateRandomUuid() = runCatching {
это оборачивать в runCatching кажется перебор.

2021-03-24 23:22 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
> +            val id = generateRandomUuid()
здесь явное дублирование и можно сильно упростить:
если adid доступен - берем его.
ошибку ловим и логируем.
если в конце id пустой, то генерируем и выходим

типа такого:
```
string id = ""
try{
val advertisingIdInfo = AdvertisingIdClient.getAdvertisingIdInfo(context)
if (!advertisingIdInfo.isLimitAdTrackingEnabled) { id = advertisingIdInfo.id }
}
catch
{
 // log
}
finally
{
 if(!id.isEmpty()) return id
 else return generateRandomUuid()
}
```

2021-03-24 23:22 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +        }.returnOnException { "" }
вот здесь не очень понятно. 
если этот метод вернет пустой deviceUUID, то у нас он сохранится и будет навсегда пустой.
запросы будут падать и ничего работать не будет.
при этом кажется что внутри этот метод должен быть написан так, что он гарантированно возвращал значение, тогда runCatching отсюда можно убрать

2021-03-24 23:26 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        var eventKeys = DbManager.getFilteredEventsKeys()
вот здесь, перед тем, как даже начинать читать ключи - надо проверить, что сдк прошло первичную инициализацию, иначе кидать исключение (которое ниже отловится и залогируется), потому что если разбор стартует раньше первичной инициализации - это некорретный код

2021-03-25 09:23 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
> +        urlQueries.toUrlQueryString()
не поняла замечания

2021-03-25 09:27 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        if (configuration == null) {
эта проверка нужна для того случая, если разработчик добавил событие в сдк до того, как вызовет инициализацию с правильными параметрами (напомню, что метод `init` может бросить `InitializeMindboxException` если параметры сонфигурации не пройдут валидацию)

2021-03-25 09:29 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            MindboxEventManager.sendEventsIfExist(context)
оговаривали что без инициализации воркер не будет стартовать - на это есть проверка конфигураций выше в замечании. могу добавить дополнительную проверку

2021-03-25 09:38 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            DbManager.saveConfigurations(configuration)
если я правильно понимаю, ты говоришь о полях которые я сохраняю в персистентное хранилище и об обьекте конфигураций, которые сохраняю в бд. Первое дешевое и я использую их для проверок сохраненных значений при инициализации (первичной или повторной), второе - полный пакет конфигураций для формирования запросов на сервер. Из значений, которые хранятся в двух местах - только `installationId` и `deviceUuid` - кажется мы оставляли их в таком виде из-за возможной миграции + потому что это необязательные поля. Хранятся эти поля в персистентном хранилище только для инициализации конфигурации

2021-03-25 09:43 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        var eventKeys = DbManager.getFilteredEventsKeys()
воркер не стартует раньше первичной инициализации из-за проверки ниже. подниму ее выше

2021-03-25 12:00 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            DbManager.saveConfigurations(configuration)
Нужно убрать поля, продублированные в преференсах и в БД и сохранять конфигурации только после сохранения ивента перв. инициализации в БД

2021-03-30 10:25 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/services/MindboxMessagingService.kt
> +internal class MindboxMessagingService : FirebaseMessagingService() {
удалено

2021-03-30 10:25 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/AndroidManifest.xml
> +<!--    <application>-->
удалено

2021-03-30 10:26 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/GatewayManager.kt
> +        urlQueries.toUrlQueryString()
удалено

2021-03-30 10:27 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
> +                MindboxLogger.d(this, "Event $key was deleted to queue")
изменено

2021-03-30 10:27 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            MindboxEventManager.sendEventsIfExist(context)
убрала выше

2021-03-30 10:29 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
> +    private fun generateRandomUuid() = runCatching {
удалено

2021-03-30 10:39 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        var eventKeys = DbManager.getFilteredEventsKeys()
подняла проверку выше

2021-03-30 10:39 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        if (configuration == null) {
подняла проверку выше

2021-03-30 10:41 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +        }.returnOnException { "" }
убрала runCatching

2021-03-30 10:53 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/IdentifierManager.kt
> +            val id = generateRandomUuid()
Изменила

2021-03-31 07:20 UTC, peter-nikitin commented
@umbrellait-alexandra-batanova какой тут статус? когда смрежите?

2021-03-31 09:16 UTC, umbrellait-alexandra-batanova commented
как только пройдут тесты

2021-04-05 14:14 UTC, umbrellait-alexandra-batanova approved these changes

2021-04-05 16:01 UTC, peter-nikitin commented
@umbrellait-alexandra-batanova @provan  что нам тут мешает смержить?

2021-04-06 00:11 UTC, provan requested changes
ряд предыдущих замечаний не исправлен

2021-04-06 09:47 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +                    MindboxEventManager.sendEventsIfExist(context)
насколько я помню мы пришли как раз к тому чтобы оставить вызов этого метода только для вторичной инициализации, тк в первичной он и так вызовется после получения идентификаторов, а для вторичной - не обязательно

2021-04-06 10:20 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        var eventKeys = DbManager.getFilteredEventsKeys()
мы обсудили что в данном контексте это и есть проверка на пустоту конфигураций. конфигурации будут пустыми если первичная инициализация не пройдена. могу добавить двойную проверку на пустоту конфигураций и флаг пройденной первичной инициализации, но кажется что это избыточно

2021-04-06 10:22 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
> +                    return@forEach
ошибки нет, но else действительно лишний - уберем

2021-04-08 19:00 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
> +            val keyTimeStamp = this.substringBefore(";", "0")
вынесла в отдельный метод

2021-04-08 19:22 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
> +            val filteredList = ArrayList(this) //coping of list
убрала внутрь проверки

2021-04-08 21:58 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            if ((isTokenAvailable && firebaseToken != MindboxPreferences.firebaseToken) || isNotificationEnabled != MindboxPreferences.isNotificationEnabled) {
на стороне сервера перед записью в бд нет проверок? 
токен будет пустой только если сдк не смог его получить, также рядом и соответствующее поле которое говорит о доступности токена. Последнее говорит о том, что токен недоступен и передает значение `false` когда Firebase отдал пустой токен. Мне показалось что для этого и нужно это поле. Иначе, как ты видишь логику, в том случае, когда токен вернулся от Firebase пустой, но и разрешения поменялись?

2021-04-08 22:06 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/DbManager.kt
> +    internal fun removeConfiguration() {
убрала в модуль тестов

2021-04-08 22:06 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/repository/MindboxPreferences.kt
> +    internal fun clear() {
убрала в модуль тестов

2021-04-09 00:08 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        var eventKeys = DbManager.getFilteredEventsKeys()
я считаю, что первой должна быть проверка на первичную инициализацию - т.к. этот флаг явно говорит, что она пройдена или нет.
а если нужно еще дополнительно защититься от пустой конфигурации (по какой-то причине), то можно ее оставить

2021-04-09 00:12 UTC, provan commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            if ((isTokenAvailable && firebaseToken != MindboxPreferences.firebaseToken) || isNotificationEnabled != MindboxPreferences.isNotificationEnabled) {
это не про firebase или сервер, 
это про то, что мы отдаем клиентам публичную ручку, куда они могут передать токен, а могут пустую строку вместо токена и оно придет сюда и отработает некорректно
надо поправить

2021-04-09 10:36 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/Mindbox.kt
> +            if ((isTokenAvailable && firebaseToken != MindboxPreferences.firebaseToken) || isNotificationEnabled != MindboxPreferences.isNotificationEnabled) {
это код не публичного метода. в публичном методе происходят проверки на `null` пустоту строки
![image](https://user-images.githubusercontent.com/53039610/114168220-a1ff1800-9938-11eb-99c5-f3baed0c70cc.png)

2021-04-09 10:39 UTC, umbrellait-alexandra-batanova commented on sdk/src/main/java/cloud/mindbox/mobile_sdk/managers/WorkerDelegate.kt
> +        var eventKeys = DbManager.getFilteredEventsKeys()
хорошо, я добавлю явную проверку

2021-05-25 13:45 UTC, merged